/**
 * README parsing and patching.
 *
 * The site renders whatever the README contains, so every patch has to keep
 * the document parseable: headings intact, no injected top-level sections,
 * no stray front-matter delimiters.
 */

import { splitEntryMeta } from '../PUBLISH/entry-meta.js';
import { isWebUrl } from '../PUBLISH/content-parse.js';

const HEADING_RE = /^(#{1,6})\s+(.*?)\s*$/;
const COMING_SOON_RE = /^[-*]\s+.*coming soon/i;
const THEMATIC_BREAK_RE = /^(---|\*\*\*|___)\s*$/;

/** Strip inline markdown so heading text can be compared to plain text. */
function stripInline(s) {
  return s
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/\*([^*]+)\*/g, '$1')
    .replace(/__([^_]+)__/g, '$1')
    .replace(/_([^_]+)_/g, '$1')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .trim();
}

/**
 * Fold a heading down to a comparison key. The README headings carry emoji
 * (## 🎓 I'm Going to Study) but the form shows plain text, so compare on
 * letters and digits only.
 */
export function normalizeHeading(s) {
  return stripInline(s)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

/** First index at or after `from` holding a heading of `level` or shallower. */
function endOfHeading(lines, from, level) {
  for (let i = from; i < lines.length; i++) {
    const m = HEADING_RE.exec(lines[i]);
    if (m && m[1].length <= level) return i;
  }
  return lines.length;
}

/**
 * Pillars are `##` sections, subsections are `###`. Each carries the line
 * range it owns so a patch can be scoped to exactly one place in the file.
 */
export function parseStructure(md) {
  const lines = md.split('\n');
  const pillars = [];
  let pillar = null;
  let section = null;

  for (let i = 0; i < lines.length; i++) {
    const m = HEADING_RE.exec(lines[i]);
    if (!m) continue;
    const level = m[1].length;

    if (level === 2) {
      pillar = {
        name: stripInline(m[2]),
        raw: m[2],
        level: 2,
        startLine: i,
        endLine: endOfHeading(lines, i + 1, 2),
        sections: [],
      };
      pillars.push(pillar);
      section = null;
    } else if (level === 3 && pillar) {
      section = {
        name: stripInline(m[2]),
        raw: m[2],
        level: 3,
        startLine: i,
        endLine: endOfHeading(lines, i + 1, 3),
      };
      pillar.sections.push(section);
    }
  }

  return {
    lines,
    // A real pillar is a `##` that owns at least one `###` subsection. The
    // README also has `##` headings that are not pillars — "Where are you
    // right now?", "Contributing", "Community & Contact" — and those are not
    // valid contribution targets.
    pillars: pillars.filter((p) => p.sections.length > 0),
  };
}

function findPillar(pillars, name) {
  const key = normalizeHeading(name);
  if (!key) return null;
  return (
    pillars.find((p) => normalizeHeading(p.name) === key) ||
    pillars.find((p) => normalizeHeading(p.name).includes(key)) ||
    null
  );
}

function findSection(pillar, name) {
  const key = normalizeHeading(name);
  if (!key) return null;
  return (
    pillar.sections.find((s) => normalizeHeading(s.name) === key) ||
    pillar.sections.find((s) => normalizeHeading(s.name).includes(key)) ||
    null
  );
}

/** Flat option list for the form's <select>, grouped by pillar. */
export function sectionOptions(md) {
  const { pillars } = parseStructure(md);
  return pillars.map((p) => ({
    pillar: p.name,
    sections: p.sections.map((s) => s.name),
  }));
}

export class PatchError extends Error {
  constructor(message, status = 400) {
    super(message);
    this.name = 'PatchError';
    this.status = status;
  }
}

/**
 * Reject anything that would let a contributor restructure the page or smuggle
 * markup. Headings are generated by the Worker from the section name, so a
 * heading inside submitted content is always a mistake or an injection.
 */
export function sanitizeContent(raw, { field = 'content', max = 4000 } = {}) {
  if (raw != null && typeof raw !== 'string') throw new PatchError(`That ${field} was not text. Please refresh the page and try again.`);
  const text = String(raw ?? '').replace(/\r\n/g, '\n').trim();

  if (!text) throw new PatchError('Please add the content you want to submit.');
  if (text.length > max) {
    throw new PatchError(`That ${field} is too long (max ${max} characters).`);
  }

  for (const line of text.split('\n')) {
    if (HEADING_RE.test(line)) {
      throw new PatchError(
        'Your text contains a heading (a line starting with #). ' +
          'Headings are managed by the site — please remove it and resubmit.'
      );
    }
    if (THEMATIC_BREAK_RE.test(line)) {
      throw new PatchError('Your text contains a "---" divider, which the site reserves. Please remove it.');
    }
  }

  if (text.includes('<!--')) {
    throw new PatchError('Your text contains an HTML comment, which is not allowed.');
  }

  // The site is written in markdown, never HTML. A tag here is a mistake or an attack.
  if (/<\/?[a-z!]/i.test(text)) {
    throw new PatchError('Your text contains HTML. Please use plain text or markdown links instead.');
  }

  // A link target becomes an href on the live site, so only web links may go in
  // (a javascript: URL would run on our origin). The site's parser enforces the
  // same rule when it renders; this keeps the bad text out of the README at all.
  for (const m of text.matchAll(/\]\(\s*([^)\s]*)/g)) {
    if (!isWebUrl(m[1])) {
      throw new PatchError('Links must start with http:// or https://. Please fix the link and resubmit.');
    }
  }

  return text
    .split('\n')
    .map((l) => l.replace(/\s+$/, ''))
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

const BULLET_RE = /^(\s*)[-*+]\s+/;
const NUMBERED_RE = /^(\s*)\d+[.)]\s+/;
// "-   [Name](url) - description" — a hyphen where the site expects an em dash.
const LINK_DASH_RE = /^(\s*-   \[[^\]]+\]\([^)]+\))\s+(?:-{1,2}|–)\s+/;

/**
 * Bring markdown from any source into the one shape the README (and the site
 * parser in PUBLISH/script.js) understands: `-   [Name](url) — description`.
 *
 * Markdown typed by hand and markdown converted from the rich text editor
 * both pass through here, so they end up byte-identical. The site only renders
 * bullet lines, so with `bulletize` a bare line becomes a bullet instead of
 * being written to the README and never shown.
 */
export function normalizeMarkdown(text, { bulletize = false } = {}) {
  const out = [];

  for (const raw of String(text ?? '').replace(/\r\n/g, '\n').split('\n')) {
    let line = raw.replace(/\s+$/, '');

    if (!line.trim()) {
      // A resource list is contiguous, so drop blank separators when bulletizing.
      if (!bulletize) out.push('');
      continue;
    }

    line = line.replace(/^(\s*)>\s?/, '$1'); // blockquote marker from rich text

    if (BULLET_RE.test(line)) {
      line = line.replace(BULLET_RE, '$1-   ');
    } else if (NUMBERED_RE.test(line)) {
      line = line.replace(NUMBERED_RE, '$1-   ');
    } else if (bulletize) {
      line = `-   ${line.trim()}`;
    }

    out.push(line.replace(LINK_DASH_RE, '$1 — '));
  }

  return out.join('\n').replace(/\n{3,}/g, '\n\n').trim();
}

/**
 * A `{closes: …; tags: …}` block is read by the site, so a malformed one must
 * not reach the README: a `closes` the site cannot parse hides the entry.
 */
export function assertEntryMeta(markdown) {
  for (const line of String(markdown).split('\n')) {
    const { errors } = splitEntryMeta(line.replace(BULLET_RE, ''));
    if (errors.length) {
      throw new PatchError(
        `The {…} block at the end of "${line.trim().slice(0, 60)}" is not valid: ${errors[0]} ` +
          'Example: {closes: 2026-11-30; tags: bursary, deadline}'
      );
    }
  }
}

/**
 * Contributor handle is optional and used only for credit. Keep it inert, and
 * keep personal information out: the project explicitly asks contributors not
 * to post contact details, so catch the obvious cases here rather than relying
 * on the reviewer to notice.
 */
export function sanitizeHandle(raw) {
  if (raw != null && typeof raw !== 'string') throw new PatchError('Please use only letters, numbers, spaces and . - _ @ / ( ) in your name.');
  const text = String(raw ?? '').trim();
  if (!text) return '';
  if (text.length > 60) throw new PatchError('Please keep your name under 60 characters.');
  if (!/^[\w .\-@/()']+$/.test(text)) {
    throw new PatchError('Please use only letters, numbers, spaces and . - _ @ / ( ) in your name.');
  }
  // Allows "@thandi" but not "thandi@example.com" — the difference is whether
  // something domain-shaped follows the @.
  if (/[^\s@]+@[^\s@]+\.[^\s@]+/.test(text)) {
    throw new PatchError('Please do not include an email address. Your name alone is enough for credit.');
  }
  // Long unbroken digit runs are phone numbers or SA ID numbers.
  if (/\d{9,}/.test(text)) {
    throw new PatchError('That looks like a phone number or ID number. Please leave it out.');
  }
  return text;
}

/**
 * Locate `needle` allowing for sloppy whitespace, because contributors paste
 * from the rendered site where "-   [NSFAS](url)" and "- [NSFAS](url)" are
 * visually identical but not byte-identical.
 */
function locate(haystack, needle) {
  const first = haystack.indexOf(needle);
  if (first !== -1) {
    let count = 0;
    let at = first;
    while (at !== -1) {
      count++;
      at = haystack.indexOf(needle, at + 1);
    }
    return { index: first, length: needle.length, count };
  }

  const escaped = needle
    .trim()
    .split(/\s+/)
    .map((part) => part.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'))
    .join('\\s+');
  if (!escaped) return { index: -1, count: 0 };

  const re = new RegExp(escaped, 'g');
  const matches = [...haystack.matchAll(re)];
  if (matches.length === 0) return { index: -1, count: 0 };

  return { index: matches[0].index, length: matches[0][0].length, count: matches.length };
}

/** Bound a search to a section's own line range, ignoring the heading itself. */
function scopeFor(md, pillarName, sectionName) {
  const { lines, pillars } = parseStructure(md);
  if (!sectionName) return { start: 0, end: md.length, pillar: null, section: null };

  const pillar = findPillar(pillars, pillarName);
  if (!pillar) throw new PatchError(`Could not find a section called "${pillarName}" in the README.`);

  const section = findSection(pillar, sectionName);
  if (!section) {
    throw new PatchError(
      `Could not find "${sectionName}" under "${pillar.name}". ` +
        `It may have been renamed — reload the page and pick again.`
    );
  }

  // Character offset of the start of a given line.
  const offsetOf = (lineIndex) =>
    lines.slice(0, lineIndex).reduce((n, l) => n + l.length + 1, 0);

  return {
    start: offsetOf(section.startLine + 1),
    end: offsetOf(section.endLine),
    pillar,
    section,
  };
}

/**
 * Flow 1 — correction. Swap the submitted "original" text for the
 * "replacement", scoped to the target section so an identical string
 * elsewhere in the README can't be hit by accident.
 */
export function applyEdit(md, { pillar, section, original, replacement }) {
  const before = sanitizeContent(original, { field: 'original text', max: 2000 });
  // If the line being corrected is a bullet, the correction must be one too.
  const after = normalizeMarkdown(sanitizeContent(replacement, { field: 'correction', max: 4000 }), {
    bulletize: BULLET_RE.test(before) || NUMBERED_RE.test(before),
  });
  assertEntryMeta(after);

  // Compare ignoring spacing, so "- x" vs "-   x" is not counted as a change.
  const flat = (s) => s.replace(/\s+/g, ' ');
  if (flat(before) === flat(after)) {
    throw new PatchError('The correction is identical to the original text — nothing to change.');
  }

  const { start, end, pillar: foundPillar, section: foundSection } = scopeFor(md, pillar, section);
  const scope = md.slice(start, end);
  const hit = locate(scope, before);

  if (hit.count === 0) {
    throw new PatchError(
      'Could not find that text in the chosen section. Copy it exactly as it appears, ' +
        'including the dash, and try again.'
    );
  }
  if (hit.count > 1) {
    throw new PatchError(
      `That text appears ${hit.count} times in the chosen section. ` +
        `Include a bit more of the surrounding text so the right one is replaced.`
    );
  }

  const patchedScope = scope.slice(0, hit.index) + after + scope.slice(hit.index + hit.length);

  return {
    markdown: md.slice(0, start) + patchedScope + md.slice(end),
    replaced: before,
    // The caller needs these for the branch name, PR title and PR body, so
    // resolve them from the README rather than echoing back the form input.
    pillarName: foundPillar ? foundPillar.name : pillar || '',
    sectionName: foundSection ? foundSection.name : pillar || '',
  };
}

/**
 * Flow 2 — new resource. Append a bullet to an existing `###` section,
 * replacing a "coming soon" placeholder when one is sitting there, or create
 * a brand new `###` section under the chosen pillar.
 */
export function applyNew(md, { pillar, section, content, newSectionName }) {
  const body = normalizeMarkdown(sanitizeContent(content, { field: 'resource', max: 4000 }), {
    bulletize: true,
  });
  assertEntryMeta(body);
  const { pillars } = parseStructure(md);
  const p = findPillar(pillars, pillar);

  if (!p) throw new PatchError(`Could not find a section called "${pillar}" in the README.`);

  /* --- creating a new ### section --- */
  if (section === 'new') {
    if (!newSectionName || typeof newSectionName !== 'string' || !newSectionName.trim()) {
      throw new PatchError('Please give the new section a name.');
    }
    if (typeof newSectionName !== 'string') throw new PatchError('Please give the new section a name.');
    const name = newSectionName.trim();
    // A newline would let the name carry its own heading lines into the README.
    if (/[\r\n]/.test(name)) throw new PatchError('The section name must be a single line.');
    if (!normalizeHeading(name)) throw new PatchError('Please use some letters or numbers in the section name.');
    if (name.length > 80) throw new PatchError('Please keep the section name under 80 characters.');
    if (HEADING_RE.test(name)) throw new PatchError('The section name cannot start with #.');

    const key = normalizeHeading(name);
    if (p.sections.some((s) => normalizeHeading(s.name) === key)) {
      throw new PatchError(`"${p.name}" already has a section called "${name}". Pick it instead.`);
    }

    const lines = md.split('\n');
    // Land the new section just before the pillar's closing boundary, after
    // any trailing blank lines.
    let at = p.endLine;
    while (at > p.startLine + 1 && (lines[at - 1] ?? '').trim() === '') at--;

    const block = ['', `### ${name}`, '', body];
    lines.splice(at, 0, ...block);

    return { markdown: lines.join('\n'), pillarName: p.name, sectionName: name, createdSection: true };
  }

  /* --- adding to an existing ### section --- */
  const s = findSection(p, section);
  if (!s) {
    throw new PatchError(
      `Could not find "${section}" under "${p.name}". ` +
        `It may have been renamed — reload the page and pick again.`
    );
  }

  const lines = md.split('\n');
  const from = s.startLine + 1;
  const to = Math.min(s.endLine, lines.length);

  // Prefer filling a "coming soon" placeholder: that is exactly the slot the
  // README is asking contributors to fill.
  for (let i = from; i < to; i++) {
    if (COMING_SOON_RE.test(lines[i].trim())) {
      lines.splice(i, 1, body);
      return { markdown: lines.join('\n'), pillarName: p.name, sectionName: s.name, filledPlaceholder: true };
    }
  }

  // Otherwise append after the last line with content in this section.
  let at = from;
  for (let i = from; i < to; i++) {
    if (lines[i].trim() !== '') at = i + 1;
  }

  if (at === from) {
    // Section is empty; give it a blank line before the body.
    lines.splice(from, 0, '', body);
  } else {
    lines.splice(at, 0, body);
  }

  return { markdown: lines.join('\n'), pillarName: p.name, sectionName: s.name };
}

/**
 * Structural guard: a patch must not change which pillars exist, since the
 * whole site is driven by those four headings.
 */
export function assertStructureIntact(before, after) {
  const a = parseStructure(before).pillars.map((p) => normalizeHeading(p.name));
  const b = parseStructure(after).pillars.map((p) => normalizeHeading(p.name));

  if (a.length !== b.length || a.some((name, i) => name !== b[i])) {
    throw new PatchError(
      'This change would alter the site structure and was rejected. ' +
        'If you think a whole new top-level section is needed, open an issue and ask first.',
      422
    );
  }
}
